spring.application.name=clientes-app
server.port=8081
spring.r2dbc.url=${DB_URL:r2dbc:mysql://localhost:3306/cliente_app}
spring.r2dbc.username=root
spring.r2dbc.password=
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc=DEBUG
spring.devtools.restart.enabled=false